version: '3.1'

services:
  producer:
    network_mode: 'host'
    image: monstrillllo/producer
    environment:
      kafka_ip: '0.0.0.0:9092'

  consumer1:
    network_mode: 'host'
    image: monstrillllo/consumer
    volumes:
      - ./data/:/usr/src/app/data/
    environment:
      kafka_ip: '0.0.0.0:9092'

  consumer2:
    network_mode: 'host'
    image: monstrillllo/consumer
    volumes:
      - ./data/:/usr/src/app/data/
    environment:
      kafka_ip: '0.0.0.0:9092'

  consumer3:
    network_mode: 'host'
    image: monstrillllo/consumer
    volumes:
      - ./data/:/usr/src/app/data/
    environment:
      kafka_ip: '0.0.0.0:9092'